RM := rm -rf

USER_OBJS :=

LIBS := 
PROJ := 

O_SRCS := 
C_SRCS := 
S_SRCS := 
S_UPPER_SRCS := 
OBJ_SRCS := 
ASM_SRCS := 
PREPROCESSING_SRCS := 
OBJS := 
OBJS_AS_ARGS := 
C_DEPS := 
C_DEPS_AS_ARGS := 
EXECUTABLES := 
OUTPUT_FILE_PATH :=
OUTPUT_FILE_PATH_AS_ARGS :=
ifeq ($(OS),Windows_NT)
	SHELL := cmd.exe
	AVR_APP_PATH := C:\Program Files (x86)\Atmel\Studio\7.0\toolchain\avr8\avr8-gnu-toolchain\bin\
	EXTENSION := .exe
	INCLUDES := -I"C:\Program Files (x86)\Atmel\Studio\7.0\Packs\atmel\XMEGAC_DFP\1.1.50\include"
	BPREFIX := -B"C:\Program Files (x86)\Atmel\Studio\7.0\Packs\atmel\XMEGAC_DFP\1.1.50\gcc\dev\atxmega32c4"
else
	SHELL := /bin/bash
	AVR_APP_PATH := $(dirname `which avr-gcc`)
	EXTENSION := 
	INCLUDE :=
	BPREFIX := 
endif
# AVR_APP_PATH :=$$$AVR_APP_PATH$$$
QUOTE := "
ADDITIONAL_DEPENDENCIES:=
OUTPUT_FILE_DEP:=
LIB_DEP:=
LINKER_SCRIPT_DEP:=

# Every subdirectory with source files must be described here
SUBDIRS :=  \
../LUFA/ \
../LUFA/ \
../LUFA/Common/ \
../LUFA/Common/ \
../LUFA/Drivers/ \
../LUFA/Drivers/ \
../LUFA/Drivers/USB/ \
../LUFA/Drivers/USB/ \
../LUFA/Drivers/USB/Class/ \
../LUFA/Drivers/USB/Class/ \
../LUFA/Drivers/USB/Class/Common/ \
../LUFA/Drivers/USB/Class/Device/ \
../LUFA/Drivers/USB/Class/Device/ \
../LUFA/Drivers/USB/Core/ \
../LUFA/Drivers/USB/Core/ \
../LUFA/Drivers/USB/Core/XMEGA/ \
../LUFA/Drivers/USB/Core/XMEGA/ \
../LUFA/Drivers/USB/Core/XMEGA/Template/ \
../LUFA/Drivers/USB/Core/XMEGA/Template/


# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS +=  \
../Descriptors.c \
../helper_functions.c \
../LUFA/Drivers/USB/Class/Device/CDCClassDevice.c \
../LUFA/Drivers/USB/Core/ConfigDescriptors.c \
../LUFA/Drivers/USB/Core/DeviceStandardReq.c \
../LUFA/Drivers/USB/Core/Events.c \
../LUFA/Drivers/USB/Core/USBTask.c \
../LUFA/Drivers/USB/Core/XMEGA/Device_XMEGA.c \
../LUFA/Drivers/USB/Core/XMEGA/EndpointStream_XMEGA.c \
../LUFA/Drivers/USB/Core/XMEGA/Endpoint_XMEGA.c \
../LUFA/Drivers/USB/Core/XMEGA/Host_XMEGA.c \
../LUFA/Drivers/USB/Core/XMEGA/PipeStream_XMEGA.c \
../LUFA/Drivers/USB/Core/XMEGA/Pipe_XMEGA.c \
../LUFA/Drivers/USB/Core/XMEGA/Template/Template_Endpoint_Control_R.c \
../LUFA/Drivers/USB/Core/XMEGA/Template/Template_Endpoint_Control_W.c \
../LUFA/Drivers/USB/Core/XMEGA/Template/Template_Endpoint_RW.c \
../LUFA/Drivers/USB/Core/XMEGA/USBController_XMEGA.c \
../LUFA/Drivers/USB/Core/XMEGA/USBInterrupt_XMEGA.c \
../mcp25xx.c \
../can-bridge-ccs.c


PREPROCESSING_SRCS +=  \
../sp_driver.S


ASM_SRCS += 


OBJS +=  \
Descriptors.o \
helper_functions.o \
LUFA/Drivers/USB/Class/Device/CDCClassDevice.o \
LUFA/Drivers/USB/Core/ConfigDescriptors.o \
LUFA/Drivers/USB/Core/DeviceStandardReq.o \
LUFA/Drivers/USB/Core/Events.o \
LUFA/Drivers/USB/Core/USBTask.o \
LUFA/Drivers/USB/Core/XMEGA/Device_XMEGA.o \
LUFA/Drivers/USB/Core/XMEGA/EndpointStream_XMEGA.o \
LUFA/Drivers/USB/Core/XMEGA/Endpoint_XMEGA.o \
LUFA/Drivers/USB/Core/XMEGA/Host_XMEGA.o \
LUFA/Drivers/USB/Core/XMEGA/PipeStream_XMEGA.o \
LUFA/Drivers/USB/Core/XMEGA/Pipe_XMEGA.o \
LUFA/Drivers/USB/Core/XMEGA/Template/Template_Endpoint_Control_R.o \
LUFA/Drivers/USB/Core/XMEGA/Template/Template_Endpoint_Control_W.o \
LUFA/Drivers/USB/Core/XMEGA/Template/Template_Endpoint_RW.o \
LUFA/Drivers/USB/Core/XMEGA/USBController_XMEGA.o \
LUFA/Drivers/USB/Core/XMEGA/USBInterrupt_XMEGA.o \
mcp25xx.o \
can-bridge-ccs.o \
sp_driver.o

OBJS_AS_ARGS +=  \
Descriptors.o \
helper_functions.o \
LUFA/Drivers/USB/Class/Device/CDCClassDevice.o \
LUFA/Drivers/USB/Core/ConfigDescriptors.o \
LUFA/Drivers/USB/Core/DeviceStandardReq.o \
LUFA/Drivers/USB/Core/Events.o \
LUFA/Drivers/USB/Core/USBTask.o \
LUFA/Drivers/USB/Core/XMEGA/Device_XMEGA.o \
LUFA/Drivers/USB/Core/XMEGA/EndpointStream_XMEGA.o \
LUFA/Drivers/USB/Core/XMEGA/Endpoint_XMEGA.o \
LUFA/Drivers/USB/Core/XMEGA/Host_XMEGA.o \
LUFA/Drivers/USB/Core/XMEGA/PipeStream_XMEGA.o \
LUFA/Drivers/USB/Core/XMEGA/Pipe_XMEGA.o \
LUFA/Drivers/USB/Core/XMEGA/Template/Template_Endpoint_Control_R.o \
LUFA/Drivers/USB/Core/XMEGA/Template/Template_Endpoint_Control_W.o \
LUFA/Drivers/USB/Core/XMEGA/Template/Template_Endpoint_RW.o \
LUFA/Drivers/USB/Core/XMEGA/USBController_XMEGA.o \
LUFA/Drivers/USB/Core/XMEGA/USBInterrupt_XMEGA.o \
mcp25xx.o \
can-bridge-ccs.o \
sp_driver.o

C_DEPS +=  \
Descriptors.d \
helper_functions.d \
LUFA/Drivers/USB/Class/Device/CDCClassDevice.d \
LUFA/Drivers/USB/Core/ConfigDescriptors.d \
LUFA/Drivers/USB/Core/DeviceStandardReq.d \
LUFA/Drivers/USB/Core/Events.d \
LUFA/Drivers/USB/Core/USBTask.d \
LUFA/Drivers/USB/Core/XMEGA/Device_XMEGA.d \
LUFA/Drivers/USB/Core/XMEGA/EndpointStream_XMEGA.d \
LUFA/Drivers/USB/Core/XMEGA/Endpoint_XMEGA.d \
LUFA/Drivers/USB/Core/XMEGA/Host_XMEGA.d \
LUFA/Drivers/USB/Core/XMEGA/PipeStream_XMEGA.d \
LUFA/Drivers/USB/Core/XMEGA/Pipe_XMEGA.d \
LUFA/Drivers/USB/Core/XMEGA/Template/Template_Endpoint_Control_R.d \
LUFA/Drivers/USB/Core/XMEGA/Template/Template_Endpoint_Control_W.d \
LUFA/Drivers/USB/Core/XMEGA/Template/Template_Endpoint_RW.d \
LUFA/Drivers/USB/Core/XMEGA/USBController_XMEGA.d \
LUFA/Drivers/USB/Core/XMEGA/USBInterrupt_XMEGA.d \
mcp25xx.d \
can-bridge-ccs.d \
sp_driver.d

C_DEPS_AS_ARGS +=  \
Descriptors.d \
helper_functions.d \
LUFA/Drivers/USB/Class/Device/CDCClassDevice.d \
LUFA/Drivers/USB/Core/ConfigDescriptors.d \
LUFA/Drivers/USB/Core/DeviceStandardReq.d \
LUFA/Drivers/USB/Core/Events.d \
LUFA/Drivers/USB/Core/USBTask.d \
LUFA/Drivers/USB/Core/XMEGA/Device_XMEGA.d \
LUFA/Drivers/USB/Core/XMEGA/EndpointStream_XMEGA.d \
LUFA/Drivers/USB/Core/XMEGA/Endpoint_XMEGA.d \
LUFA/Drivers/USB/Core/XMEGA/Host_XMEGA.d \
LUFA/Drivers/USB/Core/XMEGA/PipeStream_XMEGA.d \
LUFA/Drivers/USB/Core/XMEGA/Pipe_XMEGA.d \
LUFA/Drivers/USB/Core/XMEGA/Template/Template_Endpoint_Control_R.d \
LUFA/Drivers/USB/Core/XMEGA/Template/Template_Endpoint_Control_W.d \
LUFA/Drivers/USB/Core/XMEGA/Template/Template_Endpoint_RW.d \
LUFA/Drivers/USB/Core/XMEGA/USBController_XMEGA.d \
LUFA/Drivers/USB/Core/XMEGA/USBInterrupt_XMEGA.d \
mcp25xx.d \
can-bridge-ccs.d \
sp_driver.d

OUTPUT_FILE_PATH +=can-bridge-ccs.elf

OUTPUT_FILE_PATH_AS_ARGS +=can-bridge-ccs.elf

ADDITIONAL_DEPENDENCIES:=

OUTPUT_FILE_DEP:= ./makedep.mk

LIB_DEP+= 

LINKER_SCRIPT_DEP+= 

# AVR32/GNU C Compiler
./Descriptors.o: .././Descriptors.c
	@echo Building file: $<
	@echo Invoking: AVR/GNU C Compiler : 5.4.0
	$(QUOTE)$(AVR_APP_PATH)avr-gcc$(EXTENSION)$(QUOTE)  -x c -funsigned-char -funsigned-bitfields -DDEBUG -DARCH=ARCH_XMEGA -DUSE_RAM_DESCRIPTORS -DFIXED_CONTROL_ENDPOINT_SIZE=8 -DFIXED_NUM_CONFIGURATIONS=1 -DMAX_ENDPOINT_INDEX=4 -DF_CPU=32000000 -DF_USB=48000000  $(INCLUDES)  -O1 -ffunction-sections -fdata-sections -fpack-struct -fshort-enums -mrelax -g2 -Wall -mmcu=atxmega32c4 $(BPREFIX) -c -std=gnu99 -fms-extensions -v -MD -MP -MF "$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -MT"$(@:%.o=%.o)"   -o "$@" "$<" 
	@echo Finished building: $<
	

./helper_functions.o: .././helper_functions.c
	@echo Building file: $<
	@echo Invoking: AVR/GNU C Compiler : 5.4.0
	$(QUOTE)$(AVR_APP_PATH)avr-gcc$(EXTENSION)$(QUOTE)  -x c -funsigned-char -funsigned-bitfields -DDEBUG -DARCH=ARCH_XMEGA -DUSE_RAM_DESCRIPTORS -DFIXED_CONTROL_ENDPOINT_SIZE=8 -DFIXED_NUM_CONFIGURATIONS=1 -DMAX_ENDPOINT_INDEX=4 -DF_CPU=32000000 -DF_USB=48000000  $(INCLUDES)  -O1 -ffunction-sections -fdata-sections -fpack-struct -fshort-enums -mrelax -g2 -Wall -mmcu=atxmega32c4 $(BPREFIX) -c -std=gnu99 -fms-extensions -v -MD -MP -MF "$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -MT"$(@:%.o=%.o)"   -o "$@" "$<" 
	@echo Finished building: $<
	

LUFA/Drivers/USB/Class/Device/CDCClassDevice.o: ../LUFA/Drivers/USB/Class/Device/CDCClassDevice.c
	@echo Building file: $<
	@echo Invoking: AVR/GNU C Compiler : 5.4.0
	$(QUOTE)$(AVR_APP_PATH)avr-gcc$(EXTENSION)$(QUOTE)  -x c -funsigned-char -funsigned-bitfields -DDEBUG -DARCH=ARCH_XMEGA -DUSE_RAM_DESCRIPTORS -DFIXED_CONTROL_ENDPOINT_SIZE=8 -DFIXED_NUM_CONFIGURATIONS=1 -DMAX_ENDPOINT_INDEX=4 -DF_CPU=32000000 -DF_USB=48000000  $(INCLUDES)  -O1 -ffunction-sections -fdata-sections -fpack-struct -fshort-enums -mrelax -g2 -Wall -mmcu=atxmega32c4 $(BPREFIX) -c -std=gnu99 -fms-extensions -v -MD -MP -MF "$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -MT"$(@:%.o=%.o)"   -o "$@" "$<" 
	@echo Finished building: $<
	

LUFA/Drivers/USB/Core/ConfigDescriptors.o: ../LUFA/Drivers/USB/Core/ConfigDescriptors.c
	@echo Building file: $<
	@echo Invoking: AVR/GNU C Compiler : 5.4.0
	$(QUOTE)$(AVR_APP_PATH)avr-gcc$(EXTENSION)$(QUOTE)  -x c -funsigned-char -funsigned-bitfields -DDEBUG -DARCH=ARCH_XMEGA -DUSE_RAM_DESCRIPTORS -DFIXED_CONTROL_ENDPOINT_SIZE=8 -DFIXED_NUM_CONFIGURATIONS=1 -DMAX_ENDPOINT_INDEX=4 -DF_CPU=32000000 -DF_USB=48000000  $(INCLUDES)  -O1 -ffunction-sections -fdata-sections -fpack-struct -fshort-enums -mrelax -g2 -Wall -mmcu=atxmega32c4 $(BPREFIX) -c -std=gnu99 -fms-extensions -v -MD -MP -MF "$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -MT"$(@:%.o=%.o)"   -o "$@" "$<" 
	@echo Finished building: $<
	

LUFA/Drivers/USB/Core/DeviceStandardReq.o: ../LUFA/Drivers/USB/Core/DeviceStandardReq.c
	@echo Building file: $<
	@echo Invoking: AVR/GNU C Compiler : 5.4.0
	$(QUOTE)$(AVR_APP_PATH)avr-gcc$(EXTENSION)$(QUOTE)  -x c -funsigned-char -funsigned-bitfields -DDEBUG -DARCH=ARCH_XMEGA -DUSE_RAM_DESCRIPTORS -DFIXED_CONTROL_ENDPOINT_SIZE=8 -DFIXED_NUM_CONFIGURATIONS=1 -DMAX_ENDPOINT_INDEX=4 -DF_CPU=32000000 -DF_USB=48000000  $(INCLUDES)  -O1 -ffunction-sections -fdata-sections -fpack-struct -fshort-enums -mrelax -g2 -Wall -mmcu=atxmega32c4 $(BPREFIX) -c -std=gnu99 -fms-extensions -v -MD -MP -MF "$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -MT"$(@:%.o=%.o)"   -o "$@" "$<" 
	@echo Finished building: $<
	

LUFA/Drivers/USB/Core/Events.o: ../LUFA/Drivers/USB/Core/Events.c
	@echo Building file: $<
	@echo Invoking: AVR/GNU C Compiler : 5.4.0
	$(QUOTE)$(AVR_APP_PATH)avr-gcc$(EXTENSION)$(QUOTE)  -x c -funsigned-char -funsigned-bitfields -DDEBUG -DARCH=ARCH_XMEGA -DUSE_RAM_DESCRIPTORS -DFIXED_CONTROL_ENDPOINT_SIZE=8 -DFIXED_NUM_CONFIGURATIONS=1 -DMAX_ENDPOINT_INDEX=4 -DF_CPU=32000000 -DF_USB=48000000  $(INCLUDES)  -O1 -ffunction-sections -fdata-sections -fpack-struct -fshort-enums -mrelax -g2 -Wall -mmcu=atxmega32c4 $(BPREFIX) -c -std=gnu99 -fms-extensions -v -MD -MP -MF "$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -MT"$(@:%.o=%.o)"   -o "$@" "$<" 
	@echo Finished building: $<
	

LUFA/Drivers/USB/Core/USBTask.o: ../LUFA/Drivers/USB/Core/USBTask.c
	@echo Building file: $<
	@echo Invoking: AVR/GNU C Compiler : 5.4.0
	$(QUOTE)$(AVR_APP_PATH)avr-gcc$(EXTENSION)$(QUOTE)  -x c -funsigned-char -funsigned-bitfields -DDEBUG -DARCH=ARCH_XMEGA -DUSE_RAM_DESCRIPTORS -DFIXED_CONTROL_ENDPOINT_SIZE=8 -DFIXED_NUM_CONFIGURATIONS=1 -DMAX_ENDPOINT_INDEX=4 -DF_CPU=32000000 -DF_USB=48000000  $(INCLUDES)  -O1 -ffunction-sections -fdata-sections -fpack-struct -fshort-enums -mrelax -g2 -Wall -mmcu=atxmega32c4 $(BPREFIX) -c -std=gnu99 -fms-extensions -v -MD -MP -MF "$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -MT"$(@:%.o=%.o)"   -o "$@" "$<" 
	@echo Finished building: $<
	

LUFA/Drivers/USB/Core/XMEGA/Device_XMEGA.o: ../LUFA/Drivers/USB/Core/XMEGA/Device_XMEGA.c
	@echo Building file: $<
	@echo Invoking: AVR/GNU C Compiler : 5.4.0
	$(QUOTE)$(AVR_APP_PATH)avr-gcc$(EXTENSION)$(QUOTE)  -x c -funsigned-char -funsigned-bitfields -DDEBUG -DARCH=ARCH_XMEGA -DUSE_RAM_DESCRIPTORS -DFIXED_CONTROL_ENDPOINT_SIZE=8 -DFIXED_NUM_CONFIGURATIONS=1 -DMAX_ENDPOINT_INDEX=4 -DF_CPU=32000000 -DF_USB=48000000  $(INCLUDES)  -O1 -ffunction-sections -fdata-sections -fpack-struct -fshort-enums -mrelax -g2 -Wall -mmcu=atxmega32c4 $(BPREFIX) -c -std=gnu99 -fms-extensions -v -MD -MP -MF "$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -MT"$(@:%.o=%.o)"   -o "$@" "$<" 
	@echo Finished building: $<
	

LUFA/Drivers/USB/Core/XMEGA/EndpointStream_XMEGA.o: ../LUFA/Drivers/USB/Core/XMEGA/EndpointStream_XMEGA.c
	@echo Building file: $<
	@echo Invoking: AVR/GNU C Compiler : 5.4.0
	$(QUOTE)$(AVR_APP_PATH)avr-gcc$(EXTENSION)$(QUOTE)  -x c -funsigned-char -funsigned-bitfields -DDEBUG -DARCH=ARCH_XMEGA -DUSE_RAM_DESCRIPTORS -DFIXED_CONTROL_ENDPOINT_SIZE=8 -DFIXED_NUM_CONFIGURATIONS=1 -DMAX_ENDPOINT_INDEX=4 -DF_CPU=32000000 -DF_USB=48000000  $(INCLUDES)  -O1 -ffunction-sections -fdata-sections -fpack-struct -fshort-enums -mrelax -g2 -Wall -mmcu=atxmega32c4 $(BPREFIX) -c -std=gnu99 -fms-extensions -v -MD -MP -MF "$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -MT"$(@:%.o=%.o)"   -o "$@" "$<" 
	@echo Finished building: $<
	

LUFA/Drivers/USB/Core/XMEGA/Endpoint_XMEGA.o: ../LUFA/Drivers/USB/Core/XMEGA/Endpoint_XMEGA.c
	@echo Building file: $<
	@echo Invoking: AVR/GNU C Compiler : 5.4.0
	$(QUOTE)$(AVR_APP_PATH)avr-gcc$(EXTENSION)$(QUOTE)  -x c -funsigned-char -funsigned-bitfields -DDEBUG -DARCH=ARCH_XMEGA -DUSE_RAM_DESCRIPTORS -DFIXED_CONTROL_ENDPOINT_SIZE=8 -DFIXED_NUM_CONFIGURATIONS=1 -DMAX_ENDPOINT_INDEX=4 -DF_CPU=32000000 -DF_USB=48000000  $(INCLUDES)  -O1 -ffunction-sections -fdata-sections -fpack-struct -fshort-enums -mrelax -g2 -Wall -mmcu=atxmega32c4 $(BPREFIX) -c -std=gnu99 -fms-extensions -v -MD -MP -MF "$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -MT"$(@:%.o=%.o)"   -o "$@" "$<" 
	@echo Finished building: $<
	

LUFA/Drivers/USB/Core/XMEGA/Host_XMEGA.o: ../LUFA/Drivers/USB/Core/XMEGA/Host_XMEGA.c
	@echo Building file: $<
	@echo Invoking: AVR/GNU C Compiler : 5.4.0
	$(QUOTE)$(AVR_APP_PATH)avr-gcc$(EXTENSION)$(QUOTE)  -x c -funsigned-char -funsigned-bitfields -DDEBUG -DARCH=ARCH_XMEGA -DUSE_RAM_DESCRIPTORS -DFIXED_CONTROL_ENDPOINT_SIZE=8 -DFIXED_NUM_CONFIGURATIONS=1 -DMAX_ENDPOINT_INDEX=4 -DF_CPU=32000000 -DF_USB=48000000  $(INCLUDES)  -O1 -ffunction-sections -fdata-sections -fpack-struct -fshort-enums -mrelax -g2 -Wall -mmcu=atxmega32c4 $(BPREFIX) -c -std=gnu99 -fms-extensions -v -MD -MP -MF "$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -MT"$(@:%.o=%.o)"   -o "$@" "$<" 
	@echo Finished building: $<
	

LUFA/Drivers/USB/Core/XMEGA/PipeStream_XMEGA.o: ../LUFA/Drivers/USB/Core/XMEGA/PipeStream_XMEGA.c
	@echo Building file: $<
	@echo Invoking: AVR/GNU C Compiler : 5.4.0
	$(QUOTE)$(AVR_APP_PATH)avr-gcc$(EXTENSION)$(QUOTE)  -x c -funsigned-char -funsigned-bitfields -DDEBUG -DARCH=ARCH_XMEGA -DUSE_RAM_DESCRIPTORS -DFIXED_CONTROL_ENDPOINT_SIZE=8 -DFIXED_NUM_CONFIGURATIONS=1 -DMAX_ENDPOINT_INDEX=4 -DF_CPU=32000000 -DF_USB=48000000  $(INCLUDES)  -O1 -ffunction-sections -fdata-sections -fpack-struct -fshort-enums -mrelax -g2 -Wall -mmcu=atxmega32c4 $(BPREFIX) -c -std=gnu99 -fms-extensions -v -MD -MP -MF "$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -MT"$(@:%.o=%.o)"   -o "$@" "$<" 
	@echo Finished building: $<
	

LUFA/Drivers/USB/Core/XMEGA/Pipe_XMEGA.o: ../LUFA/Drivers/USB/Core/XMEGA/Pipe_XMEGA.c
	@echo Building file: $<
	@echo Invoking: AVR/GNU C Compiler : 5.4.0
	$(QUOTE)$(AVR_APP_PATH)avr-gcc$(EXTENSION)$(QUOTE)  -x c -funsigned-char -funsigned-bitfields -DDEBUG -DARCH=ARCH_XMEGA -DUSE_RAM_DESCRIPTORS -DFIXED_CONTROL_ENDPOINT_SIZE=8 -DFIXED_NUM_CONFIGURATIONS=1 -DMAX_ENDPOINT_INDEX=4 -DF_CPU=32000000 -DF_USB=48000000  $(INCLUDES)  -O1 -ffunction-sections -fdata-sections -fpack-struct -fshort-enums -mrelax -g2 -Wall -mmcu=atxmega32c4 $(BPREFIX) -c -std=gnu99 -fms-extensions -v -MD -MP -MF "$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -MT"$(@:%.o=%.o)"   -o "$@" "$<" 
	@echo Finished building: $<
	

LUFA/Drivers/USB/Core/XMEGA/Template/Template_Endpoint_Control_R.o: ../LUFA/Drivers/USB/Core/XMEGA/Template/Template_Endpoint_Control_R.c
	@echo Building file: $<
	@echo Invoking: AVR/GNU C Compiler : 5.4.0
	$(QUOTE)$(AVR_APP_PATH)avr-gcc$(EXTENSION)$(QUOTE)  -x c -funsigned-char -funsigned-bitfields -DDEBUG -DARCH=ARCH_XMEGA -DUSE_RAM_DESCRIPTORS -DFIXED_CONTROL_ENDPOINT_SIZE=8 -DFIXED_NUM_CONFIGURATIONS=1 -DMAX_ENDPOINT_INDEX=4 -DF_CPU=32000000 -DF_USB=48000000  $(INCLUDES)  -O1 -ffunction-sections -fdata-sections -fpack-struct -fshort-enums -mrelax -g2 -Wall -mmcu=atxmega32c4 $(BPREFIX) -c -std=gnu99 -fms-extensions -v -MD -MP -MF "$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -MT"$(@:%.o=%.o)"   -o "$@" "$<" 
	@echo Finished building: $<
	

LUFA/Drivers/USB/Core/XMEGA/Template/Template_Endpoint_Control_W.o: ../LUFA/Drivers/USB/Core/XMEGA/Template/Template_Endpoint_Control_W.c
	@echo Building file: $<
	@echo Invoking: AVR/GNU C Compiler : 5.4.0
	$(QUOTE)$(AVR_APP_PATH)avr-gcc$(EXTENSION)$(QUOTE)  -x c -funsigned-char -funsigned-bitfields -DDEBUG -DARCH=ARCH_XMEGA -DUSE_RAM_DESCRIPTORS -DFIXED_CONTROL_ENDPOINT_SIZE=8 -DFIXED_NUM_CONFIGURATIONS=1 -DMAX_ENDPOINT_INDEX=4 -DF_CPU=32000000 -DF_USB=48000000  $(INCLUDES)  -O1 -ffunction-sections -fdata-sections -fpack-struct -fshort-enums -mrelax -g2 -Wall -mmcu=atxmega32c4 $(BPREFIX) -c -std=gnu99 -fms-extensions -v -MD -MP -MF "$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -MT"$(@:%.o=%.o)"   -o "$@" "$<" 
	@echo Finished building: $<
	

LUFA/Drivers/USB/Core/XMEGA/Template/Template_Endpoint_RW.o: ../LUFA/Drivers/USB/Core/XMEGA/Template/Template_Endpoint_RW.c
	@echo Building file: $<
	@echo Invoking: AVR/GNU C Compiler : 5.4.0
	$(QUOTE)$(AVR_APP_PATH)avr-gcc$(EXTENSION)$(QUOTE)  -x c -funsigned-char -funsigned-bitfields -DDEBUG -DARCH=ARCH_XMEGA -DUSE_RAM_DESCRIPTORS -DFIXED_CONTROL_ENDPOINT_SIZE=8 -DFIXED_NUM_CONFIGURATIONS=1 -DMAX_ENDPOINT_INDEX=4 -DF_CPU=32000000 -DF_USB=48000000  $(INCLUDES)  -O1 -ffunction-sections -fdata-sections -fpack-struct -fshort-enums -mrelax -g2 -Wall -mmcu=atxmega32c4 $(BPREFIX) -c -std=gnu99 -fms-extensions -v -MD -MP -MF "$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -MT"$(@:%.o=%.o)"   -o "$@" "$<" 
	@echo Finished building: $<
	

LUFA/Drivers/USB/Core/XMEGA/USBController_XMEGA.o: ../LUFA/Drivers/USB/Core/XMEGA/USBController_XMEGA.c
	@echo Building file: $<
	@echo Invoking: AVR/GNU C Compiler : 5.4.0
	$(QUOTE)$(AVR_APP_PATH)avr-gcc$(EXTENSION)$(QUOTE)  -x c -funsigned-char -funsigned-bitfields -DDEBUG -DARCH=ARCH_XMEGA -DUSE_RAM_DESCRIPTORS -DFIXED_CONTROL_ENDPOINT_SIZE=8 -DFIXED_NUM_CONFIGURATIONS=1 -DMAX_ENDPOINT_INDEX=4 -DF_CPU=32000000 -DF_USB=48000000  $(INCLUDES)  -O1 -ffunction-sections -fdata-sections -fpack-struct -fshort-enums -mrelax -g2 -Wall -mmcu=atxmega32c4 $(BPREFIX) -c -std=gnu99 -fms-extensions -v -MD -MP -MF "$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -MT"$(@:%.o=%.o)"   -o "$@" "$<" 
	@echo Finished building: $<
	

LUFA/Drivers/USB/Core/XMEGA/USBInterrupt_XMEGA.o: ../LUFA/Drivers/USB/Core/XMEGA/USBInterrupt_XMEGA.c
	@echo Building file: $<
	@echo Invoking: AVR/GNU C Compiler : 5.4.0
	$(QUOTE)$(AVR_APP_PATH)avr-gcc$(EXTENSION)$(QUOTE)  -x c -funsigned-char -funsigned-bitfields -DDEBUG -DARCH=ARCH_XMEGA -DUSE_RAM_DESCRIPTORS -DFIXED_CONTROL_ENDPOINT_SIZE=8 -DFIXED_NUM_CONFIGURATIONS=1 -DMAX_ENDPOINT_INDEX=4 -DF_CPU=32000000 -DF_USB=48000000  $(INCLUDES)  -O1 -ffunction-sections -fdata-sections -fpack-struct -fshort-enums -mrelax -g2 -Wall -mmcu=atxmega32c4 $(BPREFIX) -c -std=gnu99 -fms-extensions -v -MD -MP -MF "$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -MT"$(@:%.o=%.o)"   -o "$@" "$<" 
	@echo Finished building: $<
	

./mcp25xx.o: .././mcp25xx.c
	@echo Building file: $<
	@echo Invoking: AVR/GNU C Compiler : 5.4.0
	$(QUOTE)$(AVR_APP_PATH)avr-gcc$(EXTENSION)$(QUOTE)  -x c -funsigned-char -funsigned-bitfields -DDEBUG -DARCH=ARCH_XMEGA -DUSE_RAM_DESCRIPTORS -DFIXED_CONTROL_ENDPOINT_SIZE=8 -DFIXED_NUM_CONFIGURATIONS=1 -DMAX_ENDPOINT_INDEX=4 -DF_CPU=32000000 -DF_USB=48000000  $(INCLUDES)  -O1 -ffunction-sections -fdata-sections -fpack-struct -fshort-enums -mrelax -g2 -Wall -mmcu=atxmega32c4 $(BPREFIX) -c -std=gnu99 -fms-extensions -v -MD -MP -MF "$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -MT"$(@:%.o=%.o)"   -o "$@" "$<" 
	@echo Finished building: $<
	

./can-bridge-ccs.o: .././can-bridge-ccs.c
	@echo Building file: $<
	@echo Invoking: AVR/GNU C Compiler : 5.4.0
	$(QUOTE)$(AVR_APP_PATH)avr-gcc$(EXTENSION)$(QUOTE)  -x c -funsigned-char -funsigned-bitfields -DDEBUG -DARCH=ARCH_XMEGA -DUSE_RAM_DESCRIPTORS -DFIXED_CONTROL_ENDPOINT_SIZE=8 -DFIXED_NUM_CONFIGURATIONS=1 -DMAX_ENDPOINT_INDEX=4 -DF_CPU=32000000 -DF_USB=48000000  $(INCLUDES)  -O1 -ffunction-sections -fdata-sections -fpack-struct -fshort-enums -mrelax -g2 -Wall -mmcu=atxmega32c4 $(BPREFIX) -c -std=gnu99 -fms-extensions -v -MD -MP -MF "$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -MT"$(@:%.o=%.o)"   -o "$@" "$<" 
	@echo Finished building: $<
	




# AVR32/GNU Preprocessing Assembler



# AVR32/GNU Assembler
./sp_driver.o: .././sp_driver.S
	@echo Building file: $<
	@echo Invoking: AVR/GNU Assembler : 5.4.0
	$(QUOTE)$(AVR_APP_PATH)avr-gcc$(EXTENSION)$(QUOTE) -Wa,-gdwarf2 -x assembler-with-cpp -c -mmcu=atxmega32c4 $(BPREFIX) $(INCLUDES) -MD -MP -MF "$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -MT"$(@:%.o=%.o)" -mrelax -Wa,-g   -o "$@" "$<" 
	@echo Finished building: $<
	





ifneq ($(MAKECMDGOALS),clean)
ifneq ($(strip $(C_DEPS)),)
-include $(C_DEPS)
endif
endif

# Add inputs and outputs from these tool invocations to the build variables 

# All Target
all: $(OUTPUT_FILE_PATH) $(ADDITIONAL_DEPENDENCIES)

$(OUTPUT_FILE_PATH): $(OBJS) $(USER_OBJS) $(OUTPUT_FILE_DEP) $(LIB_DEP) $(LINKER_SCRIPT_DEP)
	@echo Building target: $@
	@echo Invoking: AVR/GNU Linker : 5.4.0
	$(QUOTE)$(AVR_APP_PATH)avr-gcc$(EXTENSION)$(QUOTE) -o$(OUTPUT_FILE_PATH_AS_ARGS) $(OBJS_AS_ARGS) $(USER_OBJS) $(LIBS) -Wl,-Map="can-bridge-ccs.map" -Wl,--start-group -Wl,-lm  -Wl,--end-group -Wl,--gc-sections -mrelax -mmcu=atxmega32c4 $(BPREFIX)  
	@echo Finished building target: $@
	$(QUOTE)$(AVR_APP_PATH)avr-objcopy$(EXTENSION)$(QUOTE) -O ihex -R .eeprom -R .fuse -R .lock -R .signature -R .user_signatures  "can-bridge-ccs.elf" "can-bridge-ccs.hex"
	$(QUOTE)$(AVR_APP_PATH)avr-objcopy$(EXTENSION)$(QUOTE) -j .eeprom  --set-section-flags=.eeprom=alloc,load --change-section-lma .eeprom=0  --no-change-warnings -O ihex "can-bridge-ccs.elf" "can-bridge-ccs.eep" || exit 0
	$(QUOTE)$(AVR_APP_PATH)avr-objdump$(EXTENSION)$(QUOTE) -h -S "can-bridge-ccs.elf" > "can-bridge-ccs.lss"
	$(QUOTE)$(AVR_APP_PATH)avr-objcopy$(EXTENSION)$(QUOTE) -O srec -R .eeprom -R .fuse -R .lock -R .signature -R .user_signatures "can-bridge-ccs.elf" "can-bridge-ccs.srec"
	$(QUOTE)$(AVR_APP_PATH)avr-size$(EXTENSION)$(QUOTE) "can-bridge-ccs.elf"
	
	





# Other Targets
clean:
	-$(RM) $(OBJS_AS_ARGS) $(EXECUTABLES)  
	-$(RM) $(C_DEPS_AS_ARGS)   
	rm -rf "can-bridge-ccs.elf" \
			"can-bridge-ccs.a" \
			"can-bridge-ccs.hex" \
			"can-bridge-ccs.lss" \
			"can-bridge-ccs.eep" \
			"can-bridge-ccs.map" \
			"can-bridge-ccs.srec" \
			"can-bridge-ccs.usersignatures"
	